version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    $nuget_release_notes = "$env:appveyor_repo_commit_message`n`n$env:appveyor_repo_commit_message_extended".Replace("\n", "`n").TrimEnd()


    $github_release_notes = "### $nuget_release_notes".Replace("`n", "\n")


    $file = "RockLib.Diagnostics\RockLib.Diagnostics.csproj"


    $doc = [xml](Get-Content $file)


    $package_release_notes = $doc.SelectSingleNode("/Project/PropertyGroup/PackageReleaseNotes")


    $package_release_notes.InnerText = $nuget_release_notes


    $doc.Save((get-item $file))


    $package_id = $doc.SelectSingleNode("/Project/PropertyGroup/PackageId").InnerText

    $package_version = $doc.SelectSingleNode("/Project/PropertyGroup/PackageVersion").InnerText


    $package_tag = "$package_id.$package_version"


    Set-AppveyorBuildVariable -Name "release_notes" -Value $github_release_notes

    Set-AppveyorBuildVariable -Name "package_tag" -Value $package_tag


    nuget restore RockLib.Diagnostics.sln
build:
  project: RockLib.Diagnostics.sln
  verbosity: minimal
artifacts:
- path: '**\RockLib.Diagnostics.*.nupkg'
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_tag_name)
  auth_token:
    secure: yjDw1QLeuxM3Wvq9ZEJIB8JaEK/L2e7MhwrKicm3/SBh0FwbAEb3Fpg82h0fFALU
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(package_tag)
- provider: NuGet
  api_key:
    secure: n0btQo8iZJZTJ3S5vLWokuOxzv4dtYBi3cx6EbW41jTF5OfcshJs+dTMAGCTquLY
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(package_tag)
notifications:
- provider: Email
  to:
  - brianfriesen@quickenloans.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
